name: fastai_dev
channels:
- fastai
- pytorch
- defaults
dependencies:
- jupyter
- pytorch>=1.2.0
- matplotlib
- pandas
- requests
- pyyaml
- fastprogress
- pillow
- python=3.7
- pip
- pip:
  - typeguard
  - jupyter_nbextensions_configurator